version: '3.7'

services:

  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
